<nav class="navbar navbar-default navbar-static-top">

    <div class="container-fluid">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#admin-navigation-widget" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>

        <div class="collapse navbar-collapse" id="admin-navigation-widget">

            <ul class="nav navbar-nav">

                <li class="dropdown">

                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <em id="boxspaced-label">Boxspaced</em>
                    </a>

                    <ul class="dropdown-menu">
                        <li><a href="<?php echo $this->url('account'); ?>">Welcome</a></li>
                        <li><a href="<?php echo $this->url('helpdesk'); ?>">Helpdesk</a></li>
                        <li><a href="<?php echo $this->url('account', ['action' => 'logout']); ?>">Logout</a></li>
                    </ul>

                </li>

                <li class="dropdown">

                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Site
                        <b class="caret"></b>
                    </a>

                    <ul class="dropdown-menu">
                        <li><a href="<?php echo $this->url('menu'); ?>">Menu</a></li>
                        <li><a href="<?php echo $this->url('standalone'); ?>">Standalone</a></li>
                        <li><a href="<?php echo $this->url('block'); ?>">Blocks</a></li>
                        <?php if ($this->allowManageAssets) : ?>
                        <li><a href="<?php echo $this->url('asset'); ?>">Assets</a></li>
                        <?php endif; ?>
                    </ul>

                </li>

                <?php if ($this->manageableModules) : ?>
                <li class="dropdown">

                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Modules
                        <b class="caret"></b>
                    </a>

                    <ul class="dropdown-menu">
                        <?php $count = 1; foreach ($this->manageableModules as $module) : ?>
                        <li><a href="<?php echo $this->url($module, ['action' => 'manage']); ?>"><?php echo $this->escapeHtml(ucfirst(str_replace('-', ' ', $module))) ?></a></li>
                        <?php $count++; endforeach; ?>
                    </ul>

                </li>
                <?php endif; ?>

                <li class="dropdown">

                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Workflow
                        <b class="caret"></b>
                    </a>

                    <ul class="dropdown-menu">
                        <?php if ($this->allowViewAuthoring) : ?>
                        <li><a href="<?php echo $this->url('workflow', ['action' => 'authoring']); ?>">Authoring</a></li>
                        <?php endif; ?>
                        <?php if ($this->allowViewPublishing) : ?>
                        <li><a href="<?php echo $this->url('workflow', ['action' => 'publishing']); ?>">Publishing</a></li>
                        <?php endif; ?>
                    </ul>

                </li>

            </ul>
        </div>
    </div>
</nav>
