<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Idea Store CMS</title>
        <link rel="stylesheet" href="/css/admin.css" media="screen" />
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle() ?>
    </head>
    <body>
        <?php echo $this->adminNavigation ?>
        <div class="container">
            <?php echo $this->messages() ?>
            <?php echo $this->content; ?>
        </div>
        <script src="/js/admin.js"></script>
        <?php echo $this->inlineScript(); ?>
    </body>
</html>
